MySite/Comments/urls.py
from django.conf.urls import url
from Comments import  views

app_name='comments'
urlpatterns = [
    url(r'^comments/blog/(?P<blog_pk>[0-9]+)/$',views.comments,name='comments')
]

MySite/MessageBoard/urls.py
from django.conf.urls import url
from MessageBoard import views

app_name='messageboard'
urlpatterns = [
    url(r'^message/$',views.message_board,name='message_board'),
    url(r'^message/(?P<page>[0-9]+)/$', views.message_board, name='message_board')
]

MySite/MyBlog/urls.py
from django.conf.urls import url
from MyBlog import views

app_name='blog'
urlpatterns = [
    url(r'^$',views.index,),
    url(r'^index/$',views.index,name='index'),
    url(r'^about/$',views.about,name='about'),
    url(r'^blog/(?P<pk>[0-9]+)/$',views.detail,name='detail'),
    url(r'^tag/(?P<tag>\w+)$', views.tag, name='tag'),
    url(r'^search/$', views.search, name='search'),
    url(r'^archives/$', views.archives_html, name='archives_html'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$',views.archives,name='archives'),
    url(r'^category/(?P<title>\w+)/$',views.category,name='category'),
    url(r'^source/$',views.source,name='source'),
]

MySite/MySite/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.views.static import serve
from django.conf import settings
import MyBlog.urls
import Comments.urls
import MessageBoard.urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'',include(MyBlog.urls)),
    url(r'',include(Comments.urls)),
    url(r'',include(MessageBoard.urls)),
    url(r'^media/(?P<path>.*)$', serve, {"document_root": settings.MEDIA_ROOT}),
]

MySite/MessageBoard/models.py
from django.db import models

class Message(models.Model):
    name = models.CharField(max_length=10)
    email = models.EmailField(max_length=32,null=True,blank=True)
    url = models.URLField(max_length=50,null=True,blank=True)
    content = models.TextField()
    created_time=models.DateTimeField(auto_now_add=True)
    parent_comment = models.ForeignKey(to='self',null=True,blank=True)
    avatar = models.ImageField(upload_to="boardavatars/", default="boardavatars/default.png",blank=True,null=True,)


    def __str__(self):
        return self.name + self.content

    class Meta:
        db_table='message'

MySite/MyBlog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from bs4 import BeautifulSoup
import markdown


class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    class Meta:
        db_table="category"


class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    class Meta:
        db_table="tag"

class Article(models.Model):
    title = models.CharField(max_length=70)
    body = models.TextField()
    created_time = models.DateTimeField()
    modified_time = models.DateTimeField()
    excerpt = models.CharField(max_length=200, blank=True)
    category = models.ForeignKey(Category)
    tags = models.ManyToManyField(Tag, blank=True)
    author = models.ForeignKey(User)
    #是否是置顶
    stick=models.BooleanField()
    quantity = models.IntegerField(default=0)


    def get_absolute_url(self):
        return reverse("blog:detail",kwargs={'pk':self.pk})

    def quantity_raise(self):
        self.quantity += 1
        self.save(update_fields=['quantity'])

    def save(self,*args,**kwargs):

        #如果没有填写摘要,自动生成摘要
        if not self.excerpt:
            md = markdown.Markdown(extensions=[
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',
            ])
            body = md.convert(self.body)
            soup = BeautifulSoup(body,'html.parser')
            self.excerpt = soup.text[:54]
        super(Article,self).save(*args,**kwargs)

    def __str__(self):
        return self.title

    class Meta:
        db_table="article"

MySite/MessageBoard/forms.py
from django.forms import ModelForm,TextInput,EmailInput,URLInput,Textarea,FileInput
from MessageBoard import models

class MessageBoardForm(ModelForm):
    class Meta:
        model = models.Message
        fields=['name','email','url','content','avatar']
        widgets = {
            'name': TextInput(attrs={'class':"form-control",'placeholder':"nickname"}),
            'email': EmailInput(attrs={'class':"form-control",'placeholder':"email@xx.com"}),
            'url': URLInput(attrs={'class':"form-control",'placeholder':"your blog"}),
            'content': Textarea(attrs={'class':"form-control",'placeholder':"留言越屌,bug越少",'style':"resize:none",'rows':"5"}),
            'avatar': FileInput(attrs={'accept': 'image/*', 'onchange': 'verificationPicFile(this)'})

        }
        error_messages = {
            'name': {
                'required': '用户名不能为空',
                'max_length': ("您输入的昵称过长。"),
            },
            'email': {
                'required': '邮箱不能为空',
                'max_length': ("您输入的邮箱地址过长。"),
                'invalid': '您输入的邮箱格式不正确',
            },
            'url': {
                'max_length': ("您输入的博客地址过长。"),
                'invalid':'您输入的URL格式不正确',
            },
            'content': {
                'max_length': ("您输入的评论内容超出限制。"),
            },
        }

MySite/MessageBoard/views.py
from django.shortcuts import render,redirect
from MessageBoard.forms import MessageBoardForm
from MessageBoard import models
from utils.page import Pagination


def message_board(request):
    messageboardform = MessageBoardForm()
    if request.method == 'POST':
        messageboardform = MessageBoardForm(request.POST)
        if messageboardform.is_valid():
            # 校验通过，保存到数据库
            form = messageboardform.save(commit=False)
            #绑定文章
            avatar = request.FILES.get("avatar")
            if not avatar:
                avatar = 'avatars/default.png'
            form.avatar = avatar
            form.save()
            return redirect('/message/')
        else:
            print('error',request.POST)
            print(messageboardform.errors)
            message_list = models.Message.objects.all()
            context = {
                'messageboardform':messageboardform,
                'comment_list':message_list,
            }
            return render(request,'MyBlog/message_board.html',context=context)
    all_message = models.Message.objects.all().order_by('-created_time')
    current_page = request.GET.get('page')
    page_obj = Pagination(current_page=current_page,all_count=all_message.count(),base_url='/message/',per_page_num=10)
    message_list = all_message[page_obj.start:page_obj.end]
    page_html = page_obj.page_html()
    context = {
        'all_message':all_message,
        'messageboardform':messageboardform,
        'message_list':message_list,
        'page_html':page_html,
    }
    return render(request,'MyBlog/message_board.html',context=context)

MySite/MyBlog/views.py
from django.shortcuts import render, get_object_or_404, HttpResponse
from MyBlog import models
from Comments.forms import CommentForm
from django.db.models import Q
from utils import page
import markdown


def index(request):
    article_list = models.Article.objects.all().exclude(stick=True).order_by("-created_time")
    stick_article_list = models.Article.objects.filter(stick=True)
    current_page = request.GET.get('page')
    pager = page.Pagination(current_page=current_page, all_count=article_list.count(), base_url='/index/')
    article_list = article_list[pager.start:pager.end]
    page_html = pager.page_html()
    context = {
        "article_list": article_list,
        "page_html": page_html,
        "stick_article_list":stick_article_list
    }
    return render(request, 'MyBlog/index.html', context=context)


def about(request):
    return render(request, 'MyBlog/about.html')


def detail(request, pk):
    article_obj = get_object_or_404(models.Article, pk=pk)
    article_obj.quantity_raise()
    article_obj.body = markdown.markdown(article_obj.body,
                                         extensions=[
                                             'markdown.extensions.extra',
                                             'markdown.extensions.codehilite',
                                             'markdown.extensions.toc',
                                         ])

    commentform = CommentForm()
    all_comment = article_obj.comment_set.all().order_by('-created_time')
    current_page = request.GET.get('page')
    page_obj = page.Pagination(current_page=current_page, all_count=all_comment.count(), base_url="/blog/%s" % (pk),
                               per_page_num=10)
    comment_list = all_comment[page_obj.start:page_obj.end]
    page_html = page_obj.page_html()
    context = {
        'all_comment':all_comment,
        'article_obj': article_obj,
        'commentform': commentform,
        'comment_list': comment_list,
        'page_html': page_html
    }
    return render(request, 'MyBlog/detail.html', context=context)

def archives(request, year, month):
    article_list = models.Article.objects.filter(created_time__year=year,
                                                 created_time__month=month,
                                                 ).order_by('-created_time')
    return render(request, 'MyBlog/category.html', {'article_list': article_list})


def category(request, title):
    article_list = models.Article.objects.filter(category__name=title).order_by('-created_time')

    return render(request, 'MyBlog/category.html', {'article_list': article_list})


def tag(request, tag):
    article_list = models.Article.objects.filter(tags__name=tag).order_by('-created_time')
    context = {
        'article_list': article_list
    }
    return render(request, 'MyBlog/tag.html', context=context)


def search(request):
    key = request.GET.get('q')
    if request.is_ajax():
        return HttpResponse('/search/?q=' + key)
    article_list = models.Article.objects.filter(Q(title__icontains=key) or Q(body__icontains=key))

    return render(request, 'MyBlog/category.html', {'article_list': article_list})


def source(request):
    return render(request, 'MyBlog/sourcecode.html')


def archives_html(request):
    # {'2018-06-1':[obj1,obj2,obj3]}

    archive_list = models.Article.objects.dates('created_time', 'month', order='DESC')
    # 2018-06-01
    article_dic = {}

    for time in archive_list:
        year, month = str(time).split('-')[0:2]

        article_list = models.Article.objects.all().filter(created_time__year=year,
                                                           created_time__month=month, ).order_by('-created_time')
        article_dic[(str(time))] = article_list

    # for article in article_list:
    #         if time in article_dic:
    #             article_dic[str(time)].append(article)
    #         else:
    #             article_dic[str(time)] = [article,]
    # print(article_dic)
    context = {
        'archive_list': archive_list,
        'article_dic':article_dic
    }
    return render(request, 'MyBlog/archives.html', context=context)

MySite/templates/MyBlog/about.html
{% extends 'MyBlog/base.html' %}{% load static %}
{% block meta-description %}<meta name="description" content="weiheng的个人博客,记录成长历程.热衷于python，linux等，python web开发专业博客">{% endblock  %}
{% block meta-keywords %}
    <meta name="keywords" content="互联网,Python,Golang,个人博客,python语言,python教程,python笔记,Go语言,Go教程,Go笔记">{% endblock %}
{% block custom_css %}
    <link rel="stylesheet" href="{% static 'lib/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/about.css' %}">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">{% endblock %}
{% block page-main %}

    <div class="panel panel-default">
        <div class="panel-heading"><h2>关于</h2></div>
        <div class="panel-body clearfix">
            <div class="author_header clearfix">
                <img src="{% static 'img/1.jpg' %}" alt="" class="center-block">
                <div class="author">
                    <p><i class="fa fa-user"> name：</i>魏恒</p>
                    <p><i class="fa fa-envelope"> email：</i><a href="mailto:1261360292@qq.com" target="_blank">1261360292@qq.com</a>
                    </p>
                    <p><i class="fa fa-github"> github：</i><a href="https://github.com/weicunheng" target="_blank">weicunheng</a>
                    </p>
                    <p><i class="fa fa-rss-square"> cnblogs：</i><a href="https://www.cnblogs.com/weihengblog/"
                                                                   target="_blank">weiheng</a></p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

MySite/templates/MyBlog/archives.html
{% extends 'MyBlog/base.html' %}
{% load static %}
{% block meta-description %}<meta name="description" content="weiheng的个人博客,记录成长历程.热衷于python，linux等，python web开发专业博客">{% endblock  %}
{% block meta-keywords %}
    <meta name="keywords" content="互联网,Python,Golang,个人博客,python语言,python教程,python笔记,Go语言,Go教程,Go笔记">{% endblock %}
{% block custom_css %}<link rel="stylesheet" href="{% static 'css/archives.css' %}">{% endblock %}

{% block page-main %}
    <div class="panel panel-default">
        <div class="panel-heading"><h2>归档</h2></div>
        <div class="panel-body clearfix">
            {% for archive,article_list in article_dic.items %}
                <h3>{{ archive }}</h3>
                <ul>
                    {% for article in article_list %}
                        <li><a href="{% url 'blog:detail' article.pk %}">{{ article }}</a></li>
                    {% endfor %}
                </ul>
            {% endfor %}
        </div>
    </div>
{% endblock %}

MySite/templates/MyBlog/base.html
{% load staticfiles %}{% load blog_tags %}<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="weiheng">{% block meta-description %}{% endblock  %}{% block meta-keywords %}{% endblock  %}
    <meta name="robots" content="noindex,follow">
    <meta name="description" content="魏恒|个人博客">
    <title>魏恒|个人博客</title>
    <link href="{% static 'lib/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/ie10-viewport-bug-workaround.css' %}" rel="stylesheet">
    <script src="{% static 'lib/ie-emulation-modes-warning.js' %}"></script>
    <!--[if lt IE 9]>
      <script src="https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <link rel="stylesheet" href="{% static 'lib/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">{% block custom_css %}{% endblock %}
</head>
<body>
<!--
//                _ _                      _       _     _
//               (_) |                    ( )     | |   | |
//  __      _____ _| |__   ___ _ __   __ _|/ ___  | |__ | | ___   __ _
//  \ \ /\ / / _ \ | '_ \ / _ \ '_ \ / _` | / __| | '_ \| |/ _ \ / _` |
//   \ V  V /  __/ | | | |  __/ | | | (_| | \__ \ | |_) | | (_) | (_| |
//    \_/\_/ \___|_|_| |_|\___|_| |_|\__, | |___/ |_.__/|_|\___/ \__, |
//                                    __/ |                       __/ |
//                                   |___/                       |___/
-->
<!--
//                  __    __
//                 /\ \__/\ \
//   _____   __  __\ \ ,_\ \ \___     ___     ___
//  /\ '__`\/\ \/\ \\ \ \/\ \  _ `\  / __`\ /' _ `\
//  \ \ \L\ \ \ \_\ \\ \ \_\ \ \ \ \/\ \L\ \/\ \/\ \
//   \ \ ,__/\/`____ \\ \__\\ \_\ \_\ \____/\ \_\ \_\
//    \ \ \/  `/___/ \\/__/ \/_/\/_/\/___/  \/_/\/_/
//     \ \_\     /\___/
//      \/_/     \/__/
//
-->

<nav class="navbar navbar-default">
    <div class="container">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#navbar-collapse" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/index/">Weiheng's Blog</a>
            </div>

            <div class="collapse navbar-collapse" id="navbar-collapse">

                <form class="navbar-form navbar-left" action="/search/" method="get">
                    <div class="form-group">
                        <input type="text" class="form-control" name="q" placeholder="搜索...">
                    </div>
                    <button type="submit" class="btn btn-default">搜索</button>
                </form>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'blog:index' %}">首页</a></li>
                    <li><a href="{% url 'blog:archives_html' %}">归档</a></li>
                    <li><a href="{% url 'blog:source' %}">源码</a></li>
                    <li><a href="{% url 'messageboard:message_board' %}">留言板</a></li>
                    <li><a href="{% url 'blog:about' %}">关于</a></li>
                </ul>
            </div>
        </div>
    </div>
</nav>
<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
                {% block page-main %}{% endblock %}
                {% block custom-main %}{% endblock %}
            </main>
            <aside class="col-md-4">
                <div class="panel panel-default panel-search">
                    <div class="panel-heading"><h4>搜索</h4></div>
                    <div class="panel-body">
                        <form class="form-inline" action="/search/" method="get">
                            <div class="form-group">
                                <label class="sr-only" for="aside_search_text"></label>
                                <div class="input-group">
                                    <input type="text" class="form-control" id="aside_search_text" name="q" placeholder="搜索...">
                                    <div class="input-group-addon"><a id="aside_search_a">搜索</a></div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="panel panel-default panel-archives">
                    <div class="panel-heading"><h4>归档</h4></div>
                    <div class="panel-body">
                        <ul>
                            {% get_archives as archives_list %}
                            {% for archives in archives_list %}
                                <li>
                                    <i class="fa  fa-calendar-check-o"></i>
                                    <a href="{% url 'blog:archives' archives.year archives.month %}">{{ archives.year }} 年 {{ archives.month }} 月</a>
                                </li>
                            {% empty %}
                                <a href="#">暂无归档</a>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                <div class="panel panel-default panel-tags">
                    <div class="panel-heading">
                        <div class="panel-title"><h4>标签</h4></div>
                    </div>
                    <div class="panel-body ">
                        <ul>
                            {% get_tags as tag_list %}
                            {% for tag in tag_list %}
                                <li class="label label-default">
                                    <a href="{% url 'blog:tag' tag %}">{{ tag }}</a>
                                </li>
                            {% empty %}
                                <li class="label label-default">
                                    <a href="#">无TAG</a>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                <div class="panel panel-default panel-category">
                    <div class="panel-heading">
                        <h4>分类</h4>
                    </div>
                    <div class="panel-body">
                        <ul>
                            {% get_classify as category_list %}
                            {% for category in category_list %}
                                <li>
                                    <a href="{% url 'blog:category' category.name %}">{{ category.name }} <span class="post-count">({{ category.article_set.all.count }})</span></a>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </aside>
        </div>
    </div>
</div>
<footer class="blog-footer">
    <p>Blog built for Bootstrap by <a href="http://www.weiheng.site">Weiheng</a>.</p>
    <p>
        <a href="#">Back to top</a>
    </p>
</footer>
<script src="{% static 'lib/jquery.min.js' %}"></script>
<script>window.jQuery || document.write('<script src="lib/jquery.min.js"><\/script>')</script>
<script src="{% static 'lib/bootstrap.min.js' %}"></script>
<script src="{% static 'lib/holder.min.js' %}"></script>
<script src="{% static 'lib/ie10-viewport-bug-workaround.js' %}"></script>
<script>
    $("#aside_search_a").click(function () {
        key = $("#aside_search_text").val();
        $.ajax({
            url:'/search/?q='+key,
            success:function (data) {
                location.href=data;
            }
        })
    })
</script>
</body>
</html>

MySite/templates/MyBlog/detail.html
{% extends 'MyBlog/base.html' %}
{% load static %}
{% block custom_css %}
    <link rel="stylesheet" href="{% static 'css/detail.css' %}">
    <link rel="stylesheet" href="{% static 'css/github.css' %}">{% endblock %}
{% block meta-description %}
    <meta name="description" content="weiheng的个人博客,记录成长历程.热衷于python，linux等，python web开发专业博客">{% endblock %}
{% block meta-keywords %}
    <meta name="keywords" content="互联网,Python,Golang,个人博客,python语言,python教程,python笔记,Go语言,Go教程,Go笔记">{% endblock %}
{% block page-main %}
    <div class="panel panel-default">
        <div class="panel-heading"><h2>{{ article_obj.title }}</h2></div>
        <div class="panel-footer clearfix">
            <ul>
                <li class="posted-on">
                    <i class="fa fa-calendar"></i>
                    <a href="#" rel="bookmark">
                        <time class="entry-date published dt-published" itemprop="datePublished"
                              datetime="2018-06-05T11:11:56+00:00">{{ article_obj.created_time|date:'Y-m-d' }}
                        </time>
                    </a>
                </li>


                <li class="byline author p-author vcard hcard h-card" itemprop="author ">
                    <i class="fa fa-user"></i>
                    <a class="url u-url" href="#" rel="author" itemprop="url"><span
                            class=" fn p-name" itemprop="name">{{ article_obj.author }}</span></a>
                </li>
                <li class="cat-links">
                    <i class="fa fa-folder-open"></i>
                    <a href="#" rel="category">{{ article_obj.category }}</a>
                </li>
                <li class="comment">
                    <i class="fa fa-eye"></i><a href="#">{{ article_obj.quantity }} 阅读</a>
                </li>
                <div class="clearfix"></div>
            </ul>
        </div>
        <div class="panel-body">
            <div class="entry-content clearfix">
                {{ article_obj.body|safe }}
            </div>
        </div>
    </div>
{% endblock %}
{% block custom-main %}
    <section class="comment-area" id="comment-area">
        <hr>
        <h3>发表评论</h3>
        <form action="{% url 'comments:comments' article_obj.pk %}" method="post" class="comment-form"
              enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <label class="sr-only" for="id_nickname">nickname</label>
                        <div class="input-group">
                            <div class="input-group-addon"><i class="fa fa-user-o"></i></div>
                            {{ commentform.name }}
                        </div>
                        <span>{{ commentform.errors.0 }}</span>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label class="sr-only" for="id_email">email</label>
                        <div class="input-group">
                            <div class="input-group-addon"><i class="fa fa-envelope-o fa-fw"></i></div>
                            {{ commentform.email }}
                        </div>
                        <span>{{ commentform.errors.email }}</span>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label class="sr-only" for="id_url">URL</label>
                        <div class="input-group">
                            <div class="input-group-addon"><i class="fa fa-link"></i></div>
                            {{ commentform.url }}
                        </div>
                        <span>{{ commentform.errors.url }}</span>
                    </div>
                </div>
                <div class="col-md-12">
                    <label for="id_comment" class="sr-only">评论：</label>
                    {{ commentform.content }}
                    <button type="submit" id="id_comment" class="comment-btn pull-right"></button>
                    <label for="id_avatar">
                        <img id="id_avatar_img" style="width: 40px;height: 40px;"
                             src="{% static 'img/default.png' %}" title="上传头像">
                    </label>
                    <span style="display: none">{{ commentform.avatar }}</span>
                </div>
                <span>{{ commentform.erros.content.0 }}</span>
            </div>    <!-- row -->
        </form>
        <div class="comment-list-panel">
        </div>
        <h3>评论列表，共 <span>{{ all_comment.count }}</span> 条评论</h3>
        <div class="comment_list clearfix">

            <div class="botMessage messageContainer" id="three">
                <ul class="clearfix">
                    {% for comment in comment_list %}
                        <li class="comment-item clearfix">
                            <div class="">
                                <div class="avatar">
                                    <img src="/media/{{ comment.avatar }}"
                                         style="height: 40px;width: 40px;border-radius: 50%">
                                </div>
                                <div class="avatar-info">
                                    <span class="nickname"><a href="{{ comment.url }}"
                                                              title="{{ comment.name }}的博客">{{ comment.name }}</a></span>
                                    <time class="submit-date"
                                          datetime="2012-11-09T23:15:57+00:00">{{ comment.created_time|date:'Y-m-d H:i:s' }}</time>
                                </div>
                            </div>
                            <div class="msg left">
                                {{ comment.content }}
                            </div>
                        </li>
                    {% empty %}
                        <li>暂无评论</li>
                    {% endfor %}
                </ul>

            </div>
        </div>
        {% if all_comment.count > 10 %}
            <nav aria-label="Page navigation">
                <ul class="pagination">
                    {{ page_html|safe }}
                </ul>
            </nav>
        {% endif %}
    </section>
    <script src="{% static 'lib/jquery.min.js' %}"></script>
    <script>
        //图片类型验证
        function verificationPicType(file) {
            var fileTypes = [".jpg", ".png"];
            var filePath = file.value;
            //当括号里面的值为0、空字符、false 、null 、undefined的时候就相当于false
            if(filePath){
                var isNext = false;
                var fileEnd = filePath.substring(filePath.indexOf("."));
                for (var i = 0; i < fileTypes.length; i++) {
                    if (fileTypes[i] == fileEnd) {
                        isNext = true;
                        break;
                    }
                }
                if (!isNext){
                    alert('不接受此文件类型');
                    file.value = "";
                    return false;
                }
            }else {
                return false;
            }
        }

        //图片大小验证
        function verificationPicFile(file) {
            if (verificationPicType(file)){
                file.value = "";
                return false;
            }
            var fileSize = 0;
            var fileMaxSize = 2024;//1M
            var filePath = file.value;
            if(filePath){
                fileSize =file.files[0].size;
                var size = fileSize / 1024;
                if (size > fileMaxSize) {
                    alert("文件大小不能大于2M！");
                    file.value = "";
                    return false;
                }else if (size <= 0) {
                    alert("456");
                    alert("文件大小不能为0M！");
                    file.value = "";
                    return false;
                }else{
                    var fileReader = new FileReader();
                    fileReader.readAsDataURL(file.files[0]);
                    fileReader.onload = function () {
                         $("#id_avatar_img").attr("src", fileReader.result);
                    };
                    return true;
                }
            }else{
                return false;
            }
        }
    </script>
{% endblock %}

MySite/templates/MyBlog/sourcecode.html
{% extends 'MyBlog/base.html' %}
{% block meta-description %}
<meta name="description" content="weiheng的个人博客,记录成长历程.专注于互联网潮流，可用性分析，python web开发等的专业博客">
{% endblock  %}
{% block meta-keywords %}
    <meta name="keywords" content="互联网,Python,Golang,个人博客,python语言,python教程,python笔记,Go语言,Go教程,Go笔记">
{% endblock %}

{% block page-main %}
    <div class="panel panel-default">
                    <div class="panel-heading"><h2>我的开源</h2></div>
                    <div class="panel-body">
                        <p>还在整理中...</p>
                    </div>
                </div>
{% endblock %}